const DB_NAME='fitness-agent-local', STORE='state';
const $=s=>document.querySelector(s); let state={profile:{},sessions:[],messages:[],plan:null};
const openDB=()=>new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
async function load(){const db=await openDB();state=await new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).get('main');r.onsuccess=()=>res(r.result||state);r.onerror=()=>rej(r.error)});render()}
async function save(){const db=await openDB();await new Promise((res,rej)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).put(state,'main');r.onsuccess=res;r.onerror=()=>rej(r.error)})}
function today(){return new Date().toISOString().slice(0,10)}
function text(v){return String(v||'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
function markdown(v){let s=text(v);s=s.replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');s=s.replace(/^[-*] (.+)$/gm,'<span class="md-item">• $1</span>').replace(/^(\d+)\. (.+)$/gm,'<span class="md-item">$1. $2</span>');return s.replace(/\n/g,'<br>')}
function context(){const p=state.profile;const recent=state.sessions.slice(-6);return {profile:p,recentSessions:recent,previousPlan:state.plan?.raw||null}}
function formatDate(){return new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'short'}).format(new Date())}
function renderToday(){const p=state.profile||{},item=state.plan?.items?.[0];$('#hero-date').textContent=formatDate();$('#profile-name-display').textContent=p.name?`${p.name} 的训练档案`:'建立你的训练档案';$('#avatar').textContent=(p.name||'练').slice(0,1);if(item){$('#today-title').textContent=item.title;$('#today-detail').textContent=`${item.day} · ${item.detail}`;return}if(p.name){$('#today-title').textContent='生成你的第一周计划';$('#today-detail').textContent='档案已就绪。让 Agent 根据你的课表和器械排出可执行安排。';return}$('#today-title').textContent='先建立你的训练档案';$('#today-detail').textContent='告诉 Agent 你的目标、时间和器械，它才会安排训练。'}
function render(){const p=state.profile||{};$('#name').value=p.name||'';$('#age').value=p.age||'';$('#height').value=p.height||'';$('#weight').value=p.weight||'';$('#goal').value=p.goal||'增肌';$('#frequency').value=p.frequency||'3';$('#equipment').value=p.equipment||'';$('#constraints').value=p.constraints||'';$('#schedule').value=p.schedule||'';$('#session-date').value=today(); $('#greeting').textContent=p.name?`${p.name}，今天按身体状态训练。`:'先认识你，再安排训练。';$('#summary').textContent=p.goal?`目标：${p.goal}。训练 Agent 会基于你的课表、限制和反馈持续调整。`:'填写你的基础资料，Agent 才能给出真正适合你的安排。';$('#streak').textContent=state.sessions.length;$('#latest-weight').textContent=p.weight?`${p.weight} kg`:'—';const fourWeeks=state.sessions.filter(x=>Date.now()-new Date(x.date).getTime()<28*864e5&&x.completion!=='跳过');$('#sessions-28').textContent=fourWeeks.length;const rs=fourWeeks.map(x=>Number(x.rpe)).filter(Boolean);$('#avg-rpe').textContent=rs.length?(rs.reduce((a,b)=>a+b,0)/rs.length).toFixed(1):'—';$('#history').innerHTML=state.sessions.slice().reverse().map(x=>`<div class="history-item"><b>${text(x.date)} · ${text(x.completion)}</b><br><span>RPE ${text(x.rpe||'—')} ${x.note?'· '+text(x.note):''}</span></div>`).join('')||'还没有记录。第一次训练后，把重量、次数和感觉写下来。';renderToday();renderChat();renderPlan()}
function renderChat(){const root=$('#chat');root.innerHTML='';const starter=state.messages.length?[]:[{role:'agent',content:'我是你的训练 Agent。先告诉我：你想练成什么样、目前是否有疼痛或旧伤？如果已有档案，也可以直接说今天有什么临时安排。'}];[...starter,...state.messages].forEach(m=>{const t=$('#message-template').content.cloneNode(true);const el=t.querySelector('article');el.classList.toggle('me',m.role==='user');t.querySelector('b').textContent=m.role==='user'?'你':'训练 Agent';t.querySelector('p').innerHTML=markdown(m.content);root.append(t)})}
function renderPlan(){const out=$('#plan-output');if(!state.plan){out.className='plan-empty';out.textContent='先保存身体档案，然后点击下方“生成计划”。';return}out.className='';out.innerHTML=state.plan.items.map(x=>`<article class="plan-card"><b>${text(x.day)}｜${text(x.title)}</b><p>${text(x.detail)}</p></article>`).join('')+`<p class="hint">${text(state.plan.note)}</p>`}
function localPlan(){const p=state.profile;const slots=(p.schedule||'你确认的空闲时间').split(/[；;\n]/).filter(Boolean).slice(0,3);const goal=p.goal||'健康习惯';return {raw:null,items:[{day:slots[0]||'第 1 次训练',title:'全身 A（推 + 蹲）',detail:'深蹲、卧推、高位下拉、侧平举、核心。每项先用 RPE 6–7 找动作与起始重量。'},{day:slots[1]||'第 2 次训练',title:'全身 B（髋 + 拉）',detail:'罗马尼亚硬拉、上斜推、划船、分腿蹲、核心。疼痛即停止并记录。'},{day:slots[2]||'第 3 次训练',title:'全身 C（下肢 + 背）',detail:'深蹲或腿举、髋推、下拉、划船、轻推。根据本周完成度再加重量。'}],note:`这是本地规则生成的 ${goal} 起步版。填写并启用 DeepSeek Key 后，可生成更细的个性化组数、次数、饮食与临时调整建议。`}}
function parsePlan(raw){try{const o=JSON.parse(raw.match(/\{[\s\S]*\}/)?.[0]||'');if(Array.isArray(o.items))return {...o,raw};}catch{}return null}
async function askAgent(message,plan=false){const key=sessionStorage.getItem('deepseek_key');if(!key)throw new Error('请先在“设置”页粘贴 DeepSeek API Key，并点击“仅本次会话启用”。');const sys=`${AGENT_SYSTEM_PROMPT}\n\n当前用户本机上下文：${JSON.stringify(context())}`;const user=plan?`请为该用户生成本周计划。仅输出 JSON：{"items":[{"day":"时间","title":"训练主题","detail":"动作、组×次、RPE、休息、替代动作"}],"note":"饮食/恢复提醒与需确认问题"}`:message;const r=await fetch('https://api.deepseek.com/chat/completions',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${key}`},body:JSON.stringify({model:sessionStorage.getItem('deepseek_model')||'deepseek-chat',messages:[{role:'system',content:sys},{role:'user',content:user}],temperature:.5})});if(!r.ok)throw new Error(`模型请求失败：${r.status}。可能是 Key、模型名或浏览器跨域限制。`);const data=await r.json();return data.choices?.[0]?.message?.content||'没有收到模型内容。'}
function switchTab(name){document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));document.querySelector(`.tab[data-tab="${name}"]`).classList.add('active');$('#'+name).classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>switchTab(b.dataset.go));document.querySelectorAll('[data-prompt]').forEach(b=>{$('#message').value=b.dataset.prompt;$('#message').focus()});
$('#profile-form').onsubmit=async e=>{e.preventDefault();state.profile=Object.fromEntries(new FormData(e.target));await save();render();alert('档案已保存到这台设备。')};
$('#session-form').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));state.sessions.push({date:f['session-date'],completion:f.completion,rpe:f.rpe,note:f['session-note']});await save();render();alert('训练记录已保存，Agent 下次会参考它。')};
$('#save-settings').onclick=()=>{const k=$('#api-key').value.trim();if(!k)return $('#api-status').textContent='请先粘贴 API Key。';sessionStorage.setItem('deepseek_key',k);sessionStorage.setItem('deepseek_model',$('#model').value.trim()||'deepseek-chat');$('#api-key').value='';$('#api-status').textContent='已仅在本次会话启用；关闭浏览器后自动清除。'};
$('#send').onclick=async()=>{const m=$('#message').value.trim();if(!m)return;state.messages.push({role:'user',content:m});$('#message').value='';render();try{const a=await askAgent(m);state.messages.push({role:'agent',content:a});await save();render()}catch(e){state.messages.push({role:'agent',content:`${e.message}\n\n你仍可先保存档案和训练记录；未启用模型时，本地计划也可工作。`});render()}};
$('#generate-plan').onclick=async()=>{if(!state.profile.name||!state.profile.goal){alert('请先在“我的身体”页至少填写昵称和目标。');return}const btn=$('#generate-plan');btn.disabled=true;btn.textContent='生成中…';try{const raw=await askAgent('',true);state.plan=parsePlan(raw)||localPlan();if(!state.plan.raw)state.plan.note+='\n\n模型输出格式未匹配，已回退到本地安全起步方案。'}catch(e){state.plan=localPlan();state.plan.note+=`\n\n未调用模型：${e.message}`}finally{await save();render();btn.disabled=false;btn.textContent='生成 / 更新计划'}};
$('#export-data').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download=`fitness-agent-backup-${today()}.json`;a.click();URL.revokeObjectURL(a.href)};
$('#import-data').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{const imported=JSON.parse(await file.text());if(!imported||typeof imported!=='object'||!('profile'in imported))throw new Error('格式不对');state={profile:imported.profile||{},sessions:Array.isArray(imported.sessions)?imported.sessions:[],messages:Array.isArray(imported.messages)?imported.messages:[],plan:imported.plan||null};await save();render();alert('备份已恢复到这台设备。')}catch{alert('无法读取该备份文件，请确认选择的是本应用导出的 JSON 文件。')}finally{e.target.value=''}};
$('#clear-data').onclick=async()=>{if(confirm('确认清空这台设备上的全部健身 Agent 数据？此操作无法撤销。')){state={profile:{},sessions:[],messages:[],plan:null};await save();render()}};
let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('#install').hidden=false});$('#install').onclick=async()=>{if(deferred){deferred.prompt();await deferred.userChoice;deferred=null;$('#install').hidden=true}};if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');load();
